### ISSUE TITLE
Many services missing versions in dropdown

### ISSUE THREAD

**Issue by ashenden** [mesosphere/dcos-docs-site#346]
For example:

What users see: https://cl.ly/0E243G112l1h
What's in the code-base: https://cl.ly/0a2g033O1z09

@blakeandrewwood @stbof @sascala is this intended?

**Comment by sascala** [comment]
This isn't intended from our end!

@blakeandrewwood - It looks to me like only 2 versions of any given service appear in the dropdown. Is the # of versions that can appear capped somewhere? Or, more generally, is the dropdown controlled manually, or is it automatically populated by the files under the main service directories?

**Comment by sascala** [comment]
This is not intended from our end!

I see the problem, I think. This code `https://github.com/mesosphere/dcos-docs-site/blob/df411ab94ab2016e5a4f6375b1fc2c777a46123d/layouts/partials/sidebar.pug#L10` appears to search for a service doc version directory by looking for a directory that starts with `v`. This is not the case for all versions of the service docs. The short-term fix, if my hypothesis is correct, would be to prefix all service directories with `v`.

This is not desirable longterm, however, since the latest versions of the service docs have _exactly_ the same version number as the release (so, no `v` at the beginning).

I also notice that some top level pages (e.g, `cassandra/cass-auth/index.md`) don't appear. Not sure if there's a way to all that page to be displayed, if we have to put copies of that file in all the version directories and then find some way of creating a redirect that won't get stale.....

**Comment by sascala** [comment]
Maybe 90% of the way to a fix: https://github.com/mesosphere/dcos-docs-site/pull/354

**Comment by blakeandrewwood** [comment]
@ashenden @sascala @stbof 

I don't understand what is suppose to be in the version drop down, and what is not. In `./pages/services/cassandra` we have several semver based folders, and cass-auth. In `./pages/services/jenkins` there are no semver based folders so we disable the dropdown. 

I'm going create a fix that assumes we want to display the dropdown and ALL folders if there is a semver folder inside a product folder. If this create's another issue for a specific product where there is semver and other folders that should not be displayed in the dropdown, then this is a folder organization issue.

There probably should be a agnostic folder along side of the versions for topics that apply to all versions. Displaying these in the version drop down doesn't seem correct. We have the version dropdown for version and the sidebar tree for topics.

**Comment by blakeandrewwood** [comment]
Another issue is if we display `cass-auth` in the drop down

1. Version header display: We can't display the page title , because each version is formated: "Cassandra 2.0.3....", so we use the path. This means we will see `case-auth` instead of the title.
2. The sidebar tree is empty (not shown in the picture), because `cass-auth` has no children.

![configuring dc os access for cassandra mesosphere dc os documentation](https://user-images.githubusercontent.com/8361644/34316564-efd34c68-e74d-11e7-9eee-a2d42b19036b.png)
l

There's just too many special case uses with the way the sevices are organized and the way the layout is suppose to work. It's making things very brittle.

**Comment by blakeandrewwood** [comment]
And if we start displaying these version agnostic folders in the dropdown we run into styling issues.

![configuring dc os access for cassandra mesosphere dc os documentation 1](https://user-images.githubusercontent.com/8361644/34316750-b6a1a08a-e751-11e7-80f2-ed1710c8ddac.png)

**Comment by blakeandrewwood** [comment]
Added a fix for what was requested but we probably need to revisit this.

**Comment by sascala** [comment]
You mentioned creating a folder for files that are common to all versions. If that would be a fix, I can start thinking of what that name ought to be.

**Comment by stbof** [comment]
LGTM. 
![screen shot 2017-12-29 at 11 26 28 am](https://user-images.githubusercontent.com/20482960/34445817-2531d3ec-ec8b-11e7-8884-42772e49362f.png)
